input: obfuscator-alpha-release.jar
output: obfuscator-alpha-obf.jar

# The mappings created by the obfuscator are saved to this csv file
mappingFile: mappings.csv

hardExclusions:
    - arrow/
    - com/
    - io/
    - javax/
    - kotlin/
    - kotlinx/
    - org/

# Handles renaming
remap:
    # Must be specified, strategies are by default disabled
    enabled: true
    localVariableName: ""
    classPrefix: "dev/binclub/binscure/"

# Strip source file information
sourceStrip:
    enabled: true
    # Default is REMOVE, options [KEEP/REMOVE]
    lineNumbers: REMOVE

# Removes additional data created by the kotlin compiler
# WARNING: Can break the kotlin.reflect library
kotlinMetadata:
    enabled: true
    type: CENSOR

# Employs various tactics to limit or remove functionality from reverse engineering libraries
crasher:
    enabled: true
    checksums: true

# Attempts to conceal method invocations
indirection:
    enabled: false

# Encrypts constants constants and decrypts them dynamically at runtime
# Uses Context checking and may also impact application startup time
stringObfuscation:
    enabled: true

flowObfuscation:
    enabled: true
    severity: 5
    mergeMethods: BLOAT_CLASSES

optimisation:
    enabled: false
    mutableEnumValues: false

# Disable "WARNING: class was not found in the classpath" warnings
# Default is false
ignoreClassPathNotFound: false

# Use the java classloader rather than ASM to load libraries, might offer better peformane
useJavaClassloader: false
