input: ares-2.2.3-plus.jar
output: ares-2.2.3-plus-obf.jar

hardExclusions:
    - club/
    - com/
    - javassist/
    - net/
    - org/

exclusions:
    - me/tigermouthbear/ares/mixin/
    - me/tigermouthbear/clantags/
    - me/tigermouthbear/simpleevents/

# The mappings created by the obfuscator are saved to this csv file
mappingFile: mappings.csv

# Handles renaming
remap:
    # Must be specified, strategies are by default disabled
    enabled: false
    classPrefix: "me/tigermouthbear/ares/"
    localVariableName: ""
    aggressiveOverloading: false

# Strip source file information
sourceStrip:
    enabled: true
    # Default is REMOVE, options [KEEP/REMOVE]
    lineNumbers: REMOVE

# Removes additional data created by the kotlin compiler
# WARNING: Can break the kotlin.reflect library
kotlinMetadata:
    enabled: true

# Employs various tactics to limit or remove functionality from reverse engineering libraries
crasher:
    enabled: false
    checksums: false
    antiAsm: false

# Attempts to conceal method invocations
indirection:
    enabled: true

# Encrypts constants constants and decrypts them dynamically at runtime
# Uses Context checking and may also impact application startup time
stringObfuscation:
    enabled: true

flowObfuscation:
    enabled: true
    severity: 100
    mergeMethods: NONE

# Disable "WARNING: class was not found in the classpath" warnings
# Default is false
ignoreClassPathNotFound: false

libraries:
    - D:\Computing\backdoored_old\dependencies\forge-1.12.2-14.23.1.2584-srgBin.jar
    - D:\Computing\backdoored_old\dependencies\forge-1.12.2-14.23.1.2584-binpatched.jar